// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh-_00xYuvCnvlj7OG9r2-KgLhVni-b6g',
    appId: '1:296541538988:android:a29251e0a160cc737eed09',
    messagingSenderId: '296541538988',
    projectId: 'bible-quest-e00ee',
    storageBucket: 'bible-quest-e00ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJuntZrtnnPqA0fBTtBQI69J3nsuYBVeA',
    appId: '1:296541538988:ios:3e78bbb52e70c53c7eed09',
    messagingSenderId: '296541538988',
    projectId: 'bible-quest-e00ee',
    storageBucket: 'bible-quest-e00ee.firebasestorage.app',
    iosBundleId: 'com.sozo.tribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJuntZrtnnPqA0fBTtBQI69J3nsuYBVeA',
    appId: '1:296541538988:ios:3e78bbb52e70c53c7eed09',
    messagingSenderId: '296541538988',
    projectId: 'bible-quest-e00ee',
    storageBucket: 'bible-quest-e00ee.firebasestorage.app',
    iosBundleId: 'com.sozo.tribe',
  );
}
